name: color_puzzle
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_dotenv: ^6.0.0
  audioplayers: ^6.0.0
  confetti: ^0.7.0

dev_dependencies:
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.14.4

  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  mockito: ^5.6.1
  build_runner: ^2.10.4

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/audio/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#1EA5E3"
  image: assets/1.png

  android_12:
    image: assets/1.png
    color: "#1EA5E3"
